---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[deploy_certificate_tests::deploy_cert]
    attributes:
  - name: ca
    run_list:
      - recipe[deploy_certificate_tests::deploy_ca]
    attributes:
  - name: combined
    run_list:
      - recipe[deploy_certificate_tests::deploy_combined]
    attributes:
