---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
provisioner:
  data_bags_path: "test/fixtures/data_bags"
  encrypted_data_bag_secret_key_path: "test/fixtures/encrypted_data_bag_secret"

platforms:
- name: centos-6.6
- name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[deploy_certificate_tests::deploy_cert]
    attributes:
  - name: ca
    run_list:
      - recipe[deploy_certificate_tests::deploy_ca]
    attributes:
  - name: combined
    run_list:
      - recipe[deploy_certificate_tests::deploy_combined]
    attributes:
