---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[deploy_certificate_tests::deploy_cert]
    attributes:
  - name: ca
    run_list:
      - recipe[deploy_certificate_tests::deploy_ca]
    attributes:
